"""Fixed EN/HI/TA strings. Never generated by an LLM.
Hindi and Tamil text MUST be reviewed by native speakers before publishing."""
from __future__ import annotations

import re
from datetime import timedelta

LANGS = {"en": "English", "hi": "हिन्दी", "ta": "தமிழ்"}
_ORDER = ("en", "hi", "ta")
DEFAULT_LANG = "en"

_SECTIONS = {
    "ui": {
        "emergency": ("Emergency? Call 112 now.", "आपातकाल? अभी 112 पर कॉल करें।", "அவசரநிலையா? இப்போதே 112-ஐ அழைக்கவும்."),
        "footer": ("Unofficial helper app. Not affiliated with the Government of India or PM-RAHAT.",
                   "यह एक अनौपचारिक सहायक ऐप है। इसका भारत सरकार या PM-RAHAT से कोई संबंध नहीं है।",
                   "இது அதிகாரப்பூர்வமற்ற உதவி செயலி. இந்திய அரசு அல்லது PM-RAHAT உடன் தொடர்பு இல்லை."),
        "disclaimer": ("Information only, not legal or medical advice. Confirm with the hospital, police or District Collector.",
                       "यह केवल जानकारी है, कानूनी या चिकित्सीय सलाह नहीं। अस्पताल, पुलिस या जिला कलेक्टर से पुष्टि करें।",
                       "இது தகவல் மட்டுமே; சட்ட அல்லது மருத்துவ ஆலோசனை அல்ல. மருத்துவமனை, காவல்துறை அல்லது மாவட்ட ஆட்சியரிடம் உறுதிசெய்யவும்."),
        "source_note": ("Based on public PM-RAHAT scheme information. Rules can change; confirm current rules with the hospital, police or officials.",
                        "सार्वजनिक PM-RAHAT योजना जानकारी पर आधारित। नियम बदल सकते हैं; वर्तमान नियम अस्पताल, पुलिस या अधिकारियों से पूछें।",
                        "பொதுவில் கிடைக்கும் PM-RAHAT திட்டத் தகவலின் அடிப்படையில். விதிகள் மாறலாம்; தற்போதைய விதிகளை மருத்துவமனை, காவல்துறை அல்லது அதிகாரிகளிடம் உறுதிசெய்யவும்."),
        "summary_title": ("RAHAT Saathi summary", "RAHAT Saathi सारांश", "RAHAT Saathi சுருக்கம்"),
        "status": ("Status", "स्थिति", "நிலை"),
        "why": ("Why", "कारण", "காரணங்கள்"),
        "deadlines": ("Deadlines", "समय सीमाएँ", "கால வரம்புகள்"),
        "next_steps": ("What to do next", "आगे क्या करें", "அடுத்து செய்ய வேண்டியவை"),
        "escalation": ("Who to approach", "किससे संपर्क करें", "யாரை அணுக வேண்டும்"),
        "documents": ("Documents to keep", "रखने योग्य दस्तावेज़", "வைத்திருக்க வேண்டிய ஆவணங்கள்"),
        "generated": ("Generated", "तैयार किया गया", "உருவாக்கப்பட்டது"),
        "checklist_note": ("This is a common list, not an official one. Ask the hospital and police what they need.",
                           "यह एक सामान्य सूची है, आधिकारिक सूची नहीं। अस्पताल और पुलिस से पूछें कि उन्हें क्या चाहिए।",
                           "இது பொதுவான பட்டியல், அதிகாரப்பூர்வ பட்டியல் அல்ல. மருத்துவமனை மற்றும் காவல்துறையிடம் அவர்களுக்கு என்ன தேவை என்று கேளுங்கள்."),
        "no_description": ("(no description available)", "(विवरण उपलब्ध नहीं)", "(விளக்கம் இல்லை)"),
    },
    "status": {
        "likely_eligible": ("Likely eligible", "संभवतः पात्र", "பெரும்பாலும் தகுதி உள்ளது"),
        "at_risk": ("At risk", "पात्रता खतरे में", "தகுதி ஆபத்தில் உள்ளது"),
        "likely_not_eligible": ("Likely not eligible", "संभवतः पात्र नहीं", "பெரும்பாலும் தகுதி இல்லை"),
        "need_more_information": ("Need more information", "और जानकारी चाहिए", "மேலும் தகவல் தேவை"),
    },
    "reason": {
        "no_motor_vehicle": ("The scheme covers accidents involving a motor vehicle. You said no motor vehicle was involved.",
                             "यह योजना मोटर वाहन से जुड़ी दुर्घटनाओं के लिए है। आपने बताया कि कोई मोटर वाहन शामिल नहीं था।",
                             "இந்தத் திட்டம் மோட்டார் வாகனம் தொடர்புடைய விபத்துகளுக்கானது. மோட்டார் வாகனம் சம்பந்தப்படவில்லை என்று கூறினீர்கள்."),
        "motor_vehicle_unsure": ("It is not clear whether a motor vehicle was involved. The scheme covers motor-vehicle accidents.",
                                 "यह स्पष्ट नहीं है कि मोटर वाहन शामिल था या नहीं। योजना मोटर वाहन दुर्घटनाओं के लिए है।",
                                 "மோட்டார் வாகனம் தொடர்புடையதா என்பது தெளிவாக இல்லை. இத்திட்டம் மோட்டார் வாகன விபத்துகளுக்கானது."),
        "motor_vehicle_missing": ("We do not yet know if a motor vehicle was involved.",
                                  "हमें अभी नहीं पता कि मोटर वाहन शामिल था या नहीं।",
                                  "மோட்டார் வாகனம் தொடர்புடையதா என்பது இன்னும் தெரியவில்லை."),
        "life_threatening_missing": ("We do not yet know if the injury is life-threatening. This decides the time limits.",
                                     "हमें अभी नहीं पता कि चोट जानलेवा है या नहीं। इसी से समय सीमा तय होती है।",
                                     "காயம் உயிருக்கு ஆபத்தானதா என்பது இன்னும் தெரியவில்லை. இதன் அடிப்படையில் நேர வரம்புகள் மாறும்."),
        "life_threatening_unsure": ("It is unsure whether the injury is life-threatening. We use the shorter time limits to be safe. Ask the doctor to record it.",
                                    "पक्का नहीं है कि चोट जानलेवा है या नहीं। सुरक्षा के लिए हम छोटी समय सीमा मान रहे हैं। डॉक्टर से इसे दर्ज कराएँ।",
                                    "காயம் உயிருக்கு ஆபத்தானதா என்பது உறுதியாக இல்லை. பாதுகாப்புக்காக குறுகிய நேர வரம்புகளைப் பயன்படுத்துகிறோம். மருத்துவரிடம் பதிவு செய்யச் சொல்லுங்கள்."),
        "accident_time_missing": ("We need the accident date and time to calculate deadlines.",
                                  "समय सीमा निकालने के लिए दुर्घटना की तारीख और समय चाहिए।",
                                  "கால வரம்புகளைக் கணக்கிட விபத்து நடந்த தேதி மற்றும் நேரம் தேவை."),
        "accident_in_future": ("The accident time entered is in the future. Please check it.",
                               "दर्ज दुर्घटना का समय भविष्य में है। कृपया जाँचें।",
                               "உள்ளிட்ட விபத்து நேரம் எதிர்காலத்தில் உள்ளது. சரிபார்க்கவும்."),
        "hospitalisation_time_missing": ("We need the time the victim was first admitted to hospital.",
                                         "पीड़ित को पहली बार अस्पताल में भर्ती करने का समय चाहिए।",
                                         "பாதிக்கப்பட்டவர் முதன்முதலில் மருத்துவமனையில் அனுமதிக்கப்பட்ட நேரம் தேவை."),
        "hospitalisation_before_accident": ("The hospital admission time is before the accident time. Please check both times.",
                                            "अस्पताल में भर्ती का समय दुर्घटना के समय से पहले है। दोनों समय जाँचें।",
                                            "மருத்துவமனை அனுமதி நேரம் விபத்து நேரத்துக்கு முன்பாக உள்ளது. இரண்டு நேரங்களையும் சரிபார்க்கவும்."),
        "hospitalised_after_24h": ("The victim was first admitted about {delay_h} hours after the accident. The scheme requires first hospitalisation within 24 hours.",
                                   "पीड़ित को दुर्घटना के लगभग {delay_h} घंटे बाद पहली बार भर्ती किया गया। योजना में पहली भर्ती 24 घंटे के भीतर होना ज़रूरी है।",
                                   "விபத்துக்கு சுமார் {delay_h} மணி நேரத்துக்குப் பிறகு முதல் அனுமதி நடந்தது. திட்டத்தில் முதல் அனுமதி 24 மணி நேரத்துக்குள் இருக்க வேண்டும்."),
        "hospitalised_within_24h": ("First admission was within 24 hours of the accident (about {delay_h} hours).",
                                    "पहली भर्ती दुर्घटना के 24 घंटे के भीतर हुई (लगभग {delay_h} घंटे)।",
                                    "முதல் அனுமதி விபத்துக்குப் பிறகு 24 மணி நேரத்துக்குள் நடந்தது (சுமார் {delay_h} மணி நேரம்)."),
        "hospitalisation_in_future": ("The admission time is in the future. Please check it.",
                                      "भर्ती का समय भविष्य में है। कृपया जाँचें।",
                                      "அனுமதி நேரம் எதிர்காலத்தில் உள்ளது. சரிபார்க்கவும்."),
        "cover_window_ended": ("The cashless treatment period appears to have ended on {cover_end}.",
                               "कैशलेस इलाज की अवधि {cover_end} को समाप्त हो चुकी लगती है।",
                               "பணமில்லா சிகிச்சைக் காலம் {cover_end} அன்று முடிந்திருப்பதாகத் தெரிகிறது."),
        "hospital_designated": ("The hospital is a designated hospital.",
                                "यह अस्पताल एक निर्धारित (डेज़िग्नेटेड) अस्पताल है।",
                                "இது நியமிக்கப்பட்ட (designated) மருத்துவமனை."),
        "non_designated_stabilisation_only": ("A non-designated hospital can only give stabilisation treatment under the scheme.",
                                              "गैर-निर्धारित अस्पताल योजना में केवल स्थिरीकरण (स्टेबिलाइज़ेशन) इलाज दे सकता है।",
                                              "நியமிக்கப்படாத மருத்துவமனை இத்திட்டத்தில் நிலைப்படுத்தும் (stabilisation) சிகிச்சை மட்டுமே வழங்க முடியும்."),
        "stabilisation_window_ended": ("The stabilisation period ended on {stab_end}.",
                                       "स्थिरीकरण की अवधि {stab_end} को समाप्त हो गई।",
                                       "நிலைப்படுத்தும் சிகிச்சைக் காலம் {stab_end} அன்று முடிந்தது."),
        "hospital_type_unsure": ("It is unsure whether the hospital is designated. Ask the hospital.",
                                 "यह पक्का नहीं है कि अस्पताल निर्धारित है या नहीं। अस्पताल से पूछें।",
                                 "மருத்துவமனை நியமிக்கப்பட்டதா என்பது உறுதியாக இல்லை. மருத்துவமனையிடம் கேளுங்கள்."),
        "hospital_type_missing": ("We do not yet know if the hospital is designated.",
                                  "हमें अभी नहीं पता कि अस्पताल निर्धारित है या नहीं।",
                                  "மருத்துவமனை நியமிக்கப்பட்டதா என்பது இன்னும் தெரியவில்லை."),
        "police_missing": ("We do not yet know whether the police have been informed.",
                           "हमें अभी नहीं पता कि पुलिस को सूचना दी गई या नहीं।",
                           "காவல்துறைக்குத் தகவல் தெரிவிக்கப்பட்டதா என்பது இன்னும் தெரியவில்லை."),
        "police_unsure": ("It is unsure whether the police were informed. Police confirmation is needed within the time limit.",
                          "पक्का नहीं है कि पुलिस को सूचना दी गई। समय सीमा के भीतर पुलिस की पुष्टि ज़रूरी है।",
                          "காவல்துறைக்குத் தகவல் தெரிவிக்கப்பட்டதா என்பது உறுதியாக இல்லை. நேர வரம்புக்குள் காவல்துறை உறுதிப்படுத்தல் தேவை."),
        "police_timeout": ("The police confirmation deadline ({deadline}) has passed without confirmation.",
                           "पुलिस पुष्टि की समय सीमा ({deadline}) बिना पुष्टि के बीत चुकी है।",
                           "காவல்துறை உறுதிப்படுத்தல் கால வரம்பு ({deadline}) உறுதிப்படுத்தல் இல்லாமல் முடிந்துவிட்டது."),
        "police_pending": ("Police have not been informed yet. Confirmation deadline: {deadline}.",
                           "पुलिस को अभी सूचना नहीं दी गई है। पुष्टि की अंतिम समय सीमा: {deadline}।",
                           "காவல்துறைக்கு இன்னும் தகவல் தெரிவிக்கப்படவில்லை. உறுதிப்படுத்தல் கடைசி நேரம்: {deadline}."),
        "police_time_missing": ("Police were informed, but we need the time they were informed.",
                                "पुलिस को सूचना दी गई, पर हमें सूचना का समय चाहिए।",
                                "காவல்துறைக்குத் தகவல் தெரிவிக்கப்பட்டது; ஆனால் தெரிவித்த நேரம் தேவை."),
        "police_late": ("Police were informed after the deadline ({deadline}). Ask the police and hospital what this means for the claim.",
                        "पुलिस को सूचना समय सीमा ({deadline}) के बाद दी गई। दावे पर इसका क्या असर होगा, पुलिस और अस्पताल से पूछें।",
                        "காவல்துறைக்கு கால வரம்புக்குப் ({deadline}) பிறகு தகவல் தெரிவிக்கப்பட்டது. இது கோரிக்கையை எவ்வாறு பாதிக்கும் என்பதை காவல்துறை மற்றும் மருத்துவமனையிடம் கேளுங்கள்."),
        "police_in_time": ("Police were informed within the time limit.",
                           "पुलिस को समय सीमा के भीतर सूचना दी गई।",
                           "காவல்துறைக்கு நேர வரம்புக்குள் தகவல் தெரிவிக்கப்பட்டது."),
        "hit_and_run_collector": ("Hit-and-run cases are routed to the District Collector of the accident location.",
                                  "हिट-एंड-रन मामले दुर्घटना स्थल के जिला कलेक्टर को भेजे जाते हैं।",
                                  "ஹிட்-அண்ட்-ரன் வழக்குகள் விபத்து நடந்த இடத்தின் மாவட்ட ஆட்சியருக்கு அனுப்பப்படும்."),
        "hit_and_run_unknown": ("It is unsure whether this was a hit-and-run. If the other vehicle cannot be identified, the claim goes to the District Collector.",
                                "पक्का नहीं है कि यह हिट-एंड-रन था। यदि दूसरे वाहन की पहचान न हो सके, तो दावा जिला कलेक्टर के पास जाता है।",
                                "இது ஹிட்-அண்ட்-ரன் என்பது உறுதியாக இல்லை. மற்ற வாகனத்தை அடையாளம் காண முடியாவிட்டால் கோரிக்கை மாவட்ட ஆட்சியருக்குச் செல்லும்."),
        "uninsured_collector": ("If the vehicle is uninsured, the claim goes to the District Collector of the accident location.",
                                "यदि वाहन का बीमा नहीं है, तो दावा दुर्घटना स्थल के जिला कलेक्टर के पास जाता है।",
                                "வாகனத்துக்கு காப்பீடு இல்லையென்றால் கோரிக்கை விபத்து நடந்த இடத்தின் மாவட்ட ஆட்சியருக்குச் செல்லும்."),
        # insured-unsure code was not visible to me; these aliases cover likely names
        "insured_unsure": ("It is unsure whether the vehicle is insured. If it is not, the claim goes to the District Collector.",
                           "पक्का नहीं है कि वाहन का बीमा है या नहीं। यदि नहीं है, तो दावा जिला कलेक्टर के पास जाता है।",
                           "வாகனத்துக்கு காப்பீடு உள்ளதா என்பது உறுதியாக இல்லை. இல்லையென்றால் கோரிக்கை மாவட்ட ஆட்சியருக்குச் செல்லும்."),
        "insurance_unknown": ("It is unsure whether the vehicle is insured. If it is not, the claim goes to the District Collector.",
                              "पक्का नहीं है कि वाहन का बीमा है या नहीं। यदि नहीं है, तो दावा जिला कलेक्टर के पास जाता है।",
                              "வாகனத்துக்கு காப்பீடு உள்ளதா என்பது உறுதியாக இல்லை. இல்லையென்றால் கோரிக்கை மாவட்ட ஆட்சியருக்குச் செல்லும்."),
        "insured_unknown": ("It is unsure whether the vehicle is insured. If it is not, the claim goes to the District Collector.",
                            "पक्का नहीं है कि वाहन का बीमा है या नहीं। यदि नहीं है, तो दावा जिला कलेक्टर के पास जाता है।",
                            "வாகனத்துக்கு காப்பீடு உள்ளதா என்பது உறுதியாக இல்லை. இல்லையென்றால் கோரிக்கை மாவட்ட ஆட்சியருக்குச் செல்லும்."),
    },
    "step": {
        "ask_hospital_cashless": ("Ask the hospital to treat under the PM-RAHAT cashless scheme.",
                                  "अस्पताल से कहें कि वह PM-RAHAT कैशलेस योजना के तहत इलाज करे।",
                                  "PM-RAHAT பணமில்லா திட்டத்தின் கீழ் சிகிச்சை அளிக்குமாறு மருத்துவமனையிடம் கேளுங்கள்."),
        "ask_hospital_about_other_options": ("Ask the hospital and police about other options, such as insurance or compensation claims.",
                                             "अस्पताल और पुलिस से अन्य विकल्पों के बारे में पूछें, जैसे बीमा या मुआवज़ा दावा।",
                                             "காப்பீடு அல்லது இழப்பீட்டு கோரிக்கை போன்ற மற்ற வாய்ப்புகள் பற்றி மருத்துவமனை மற்றும் காவல்துறையிடம் கேளுங்கள்."),
        "confirm_vehicle_involved": ("Confirm whether a motor vehicle was involved and make sure it is noted in the police report.",
                                     "पुष्टि करें कि मोटर वाहन शामिल था या नहीं और पुलिस रिपोर्ट में दर्ज कराएँ।",
                                     "மோட்டார் வாகனம் தொடர்புடையதா என்பதை உறுதிசெய்து காவல்துறை அறிக்கையில் பதிவு செய்யுங்கள்."),
        "move_to_designated_hospital": ("Ask the hospital and doctor about moving to a designated hospital when it is medically safe.",
                                        "जब चिकित्सकीय रूप से सुरक्षित हो, तब निर्धारित अस्पताल में ले जाने के बारे में अस्पताल और डॉक्टर से पूछें।",
                                        "மருத்துவ ரீதியாகப் பாதுகாப்பானபோது நியமிக்கப்பட்ட மருத்துவமனைக்கு மாற்றுவது பற்றி மருத்துவமனை மற்றும் மருத்துவரிடம் கேளுங்கள்."),
        "confirm_designated_hospital": ("Ask the hospital if it is a designated hospital. Dial 112 to find the nearest one.",
                                        "अस्पताल से पूछें कि वह निर्धारित अस्पताल है या नहीं। निकटतम अस्पताल जानने के लिए 112 पर कॉल करें।",
                                        "இது நியமிக்கப்பட்ட மருத்துவமனையா என்று கேளுங்கள். அருகிலுள்ளதை அறிய 112-ஐ அழைக்கவும்."),
        "get_police_confirmation": ("Make sure the police have recorded the accident and confirmed it on their system within the time limit.",
                                    "सुनिश्चित करें कि पुलिस ने दुर्घटना दर्ज कर ली है और समय सीमा के भीतर अपने सिस्टम में पुष्टि कर दी है।",
                                    "காவல்துறை விபத்தைப் பதிவு செய்து, நேர வரம்புக்குள் தங்கள் அமைப்பில் உறுதிப்படுத்தியதா என்பதை உறுதிசெய்யுங்கள்."),
        "ask_hospital_to_record_severity": ("Ask the doctor to record whether the injury is life-threatening.",
                                            "डॉक्टर से कहें कि चोट जानलेवा है या नहीं, यह दर्ज करें।",
                                            "காயம் உயிருக்கு ஆபத்தானதா என்பதை மருத்துவர் பதிவு செய்யுமாறு கேளுங்கள்."),
        "ask_hospital_about_cover_end": ("Ask the hospital about the cover end date and what to do next.",
                                         "कवर की समाप्ति तिथि और आगे क्या करना है, अस्पताल से पूछें।",
                                         "காப்பீடு முடியும் தேதி மற்றும் அடுத்து செய்ய வேண்டியது பற்றி மருத்துவமனையிடம் கேளுங்கள்."),
        "approach_district_collector": ("Contact the District Collector's office of the accident location about the claim.",
                                        "दावे के बारे में दुर्घटना स्थल के जिला कलेक्टर कार्यालय से संपर्क करें।",
                                        "கோரிக்கை குறித்து விபத்து நடந்த இடத்தின் மாவட்ட ஆட்சியர் அலுவலகத்தைத் தொடர்பு கொள்ளுங்கள்."),
        "keep_documents": ("Keep copies of all documents, bills and reports.",
                           "सभी दस्तावेज़, बिल और रिपोर्ट की प्रतियाँ सँभालकर रखें।",
                           "அனைத்து ஆவணங்கள், பில்கள் மற்றும் அறிக்கைகளின் நகல்களை பத்திரமாக வைத்திருங்கள்."),
    },
    "question": {
        "accident_at": ("When did the accident happen? (date and time)", "दुर्घटना कब हुई? (तारीख और समय)", "விபத்து எப்போது நடந்தது? (தேதி மற்றும் நேரம்)"),
        "motor_vehicle": ("Was a motor vehicle involved?", "क्या कोई मोटर वाहन शामिल था?", "மோட்டார் வாகனம் சம்பந்தப்பட்டதா?"),
        "life_threatening": ("Is the injury life-threatening (as the doctor said)?", "क्या चोट जानलेवा है (जैसा डॉक्टर ने बताया)?", "காயம் உயிருக்கு ஆபத்தானதா (மருத்துவர் கூறியபடி)?"),
        "hospitalised_at": ("When was the victim first admitted to a hospital?", "पीड़ित को पहली बार अस्पताल में कब भर्ती किया गया?", "பாதிக்கப்பட்டவர் முதன்முதலில் எப்போது மருத்துவமனையில் அனுமதிக்கப்பட்டார்?"),
        "hospital_type": ("Is the hospital a designated hospital?", "क्या यह अस्पताल निर्धारित (डेज़िग्नेटेड) अस्पताल है?", "இது நியமிக்கப்பட்ட மருத்துவமனையா?"),
        "police_informed": ("Have the police been informed?", "क्या पुलिस को सूचना दी गई है?", "காவல்துறைக்குத் தகவல் தெரிவிக்கப்பட்டதா?"),
        "police_informed_at": ("When were the police informed?", "पुलिस को कब सूचना दी गई?", "காவல்துறைக்கு எப்போது தகவல் தெரிவிக்கப்பட்டது?"),
        "hit_and_run": ("Was it a hit-and-run (other vehicle not identified)?", "क्या यह हिट-एंड-रन था (दूसरा वाहन अज्ञात)?", "இது ஹிட்-அண்ட்-ரன்னா (மற்ற வாகனம் அடையாளம் தெரியவில்லையா)?"),
        "insured": ("Is the vehicle insured?", "क्या वाहन का बीमा है?", "வாகனத்துக்கு காப்பீடு உள்ளதா?"),
        "state": ("Which state did the accident happen in?", "दुर्घटना किस राज्य में हुई?", "விபத்து எந்த மாநிலத்தில் நடந்தது?"),
    },
    "deadline": {
        "cover_end": ("Cashless treatment period ends", "कैशलेस इलाज की अवधि समाप्त", "பணமில்லா சிகிச்சைக் காலம் முடிவு"),
        "hospitalisation_deadline": ("Latest first admission to hospital", "अस्पताल में पहली भर्ती की अंतिम समय सीमा", "மருத்துவமனையில் முதல் அனுமதிக்கான கடைசி நேரம்"),
        "stabilisation_end": ("Stabilisation period ends", "स्थिरीकरण अवधि समाप्त", "நிலைப்படுத்தும் காலம் முடிவு"),
        "police_deadline": ("Police confirmation deadline", "पुलिस पुष्टि की अंतिम समय सीमा", "காவல்துறை உறுதிப்படுத்தல் கடைசி நேரம்"),
    },
    "route": {
        "hospital_and_police": ("Work through the hospital and police first.", "पहले अस्पताल और पुलिस के माध्यम से आगे बढ़ें।", "முதலில் மருத்துவமனை மற்றும் காவல்துறை வழியாகச் செயல்படுங்கள்."),
        "district_collector": ("This case may need the District Collector of the accident location.", "इस मामले में दुर्घटना स्थल के जिला कलेक्टर की ज़रूरत पड़ सकती है।", "இந்த வழக்கில் விபத்து நடந்த இடத்தின் மாவட்ட ஆட்சியர் தேவைப்படலாம்."),
    },
    "group": {
        "hospital": ("At the hospital", "अस्पताल में", "மருத்துவமனையில்"),
        "police": ("With the police", "पुलिस के पास", "காவல்துறையிடம்"),
        "insurance": ("For later insurance or compensation claims", "बाद के बीमा या मुआवज़ा दावों के लिए", "பின்னர் காப்பீடு அல்லது இழப்பீட்டு கோரிக்கைகளுக்கு"),
        "collector": ("If the claim goes to the District Collector", "यदि दावा जिला कलेक्टर के पास जाता है", "கோரிக்கை மாவட்ட ஆட்சியருக்குச் சென்றால்"),
    },
    "item": {
        "id_proof": ("Victim's ID proof, if available", "पीड़ित का पहचान पत्र, यदि उपलब्ध हो", "பாதிக்கப்பட்டவரின் அடையாள ஆவணம், இருந்தால்"),
        "admission_papers": ("Hospital admission and discharge papers", "अस्पताल में भर्ती और छुट्टी के कागज़ात", "மருத்துவமனை அனுமதி மற்றும் வெளியேற்ற ஆவணங்கள்"),
        "bills": ("All bills and receipts", "सभी बिल और रसीदें", "அனைத்து பில்கள் மற்றும் ரசீதுகள்"),
        "medical_records": ("Treatment and medical records, including the doctor's note on severity", "इलाज और चिकित्सा रिकॉर्ड, चोट की गंभीरता पर डॉक्टर के नोट सहित", "சிகிச்சை மற்றும் மருத்துவ பதிவுகள், காயத்தின் தீவிரம் குறித்த மருத்துவர் குறிப்பு உட்பட"),
        "police_report": ("Copy or acknowledgement of the police report or FIR", "पुलिस रिपोर्ट या FIR की प्रति या पावती", "காவல்துறை அறிக்கை அல்லது FIR-இன் நகல் அல்லது ஒப்புகை"),
        "accident_id": ("The accident or report number the police give you", "पुलिस द्वारा दिया गया दुर्घटना या रिपोर्ट नंबर", "காவல்துறை வழங்கும் விபத்து அல்லது அறிக்கை எண்"),
        "other_vehicle": ("Details of the other vehicle, if known (number, owner)", "दूसरे वाहन की जानकारी, यदि पता हो (नंबर, मालिक)", "மற்ற வாகனத்தின் விவரங்கள், தெரிந்தால் (எண், உரிமையாளர்)"),
        "policy": ("Copy of the vehicle insurance policy, if any", "वाहन बीमा पॉलिसी की प्रति, यदि हो", "வாகன காப்பீட்டுக் கொள்கையின் நகல், இருந்தால்"),
        "licence_rc": ("Driving licence and vehicle registration papers", "ड्राइविंग लाइसेंस और वाहन पंजीकरण के कागज़ात", "ஓட்டுநர் உரிமம் மற்றும் வாகனப் பதிவு ஆவணங்கள்"),
        "scene_photos": ("Photos of the scene and vehicles, if available", "घटनास्थल और वाहनों की तस्वीरें, यदि उपलब्ध हों", "சம்பவ இடம் மற்றும் வாகனங்களின் புகைப்படங்கள், இருந்தால்"),
        "bank_details": ("Bank account details of the claimant", "दावेदार के बैंक खाते की जानकारी", "கோரிக்கையாளரின் வங்கிக் கணக்கு விவரங்கள்"),
        "written_application": ("A written application to the District Collector", "जिला कलेक्टर को लिखित आवेदन", "மாவட்ட ஆட்சியருக்கு எழுத்துப்பூர்வ விண்ணப்பம்"),
        "copies": ("Copies of the police report, hospital papers and bills", "पुलिस रिपोर्ट, अस्पताल के कागज़ात और बिलों की प्रतियाँ", "காவல்துறை அறிக்கை, மருத்துவமனை ஆவணங்கள் மற்றும் பில்களின் நகல்கள்"),
        "witness": ("Names and contact details of witnesses, if any", "गवाहों के नाम और संपर्क विवरण, यदि हों", "சாட்சிகளின் பெயர்கள் மற்றும் தொடர்பு விவரங்கள், இருந்தால்"),
    },
}

STRINGS: dict = {lang: {} for lang in _ORDER}
for _sec, _items in _SECTIONS.items():
    for _k, _v in _items.items():
        assert len(_v) == 3, (_sec, _k)
        for _i, _l in enumerate(_ORDER):
            STRINGS[_l].setdefault(_sec, {})[_k] = _v[_i]


def norm_lang(lang) -> str:
    return lang if lang in STRINGS else DEFAULT_LANG


class _Safe(dict):
    def __missing__(self, key):
        return "—"


def fmt_dt(dt) -> str:
    s = dt.strftime("%d %b %Y, %I:%M %p")
    if dt.tzinfo is not None and dt.utcoffset() == timedelta(hours=5, minutes=30):
        s += " IST"
    return s


def t(lang, section: str, key: str, **params) -> str:
    lang = norm_lang(lang)
    s = STRINGS[lang].get(section, {}).get(key)
    if s is None:
        s = STRINGS["en"].get(section, {}).get(key)
    if s is None:
        return STRINGS[lang]["ui"]["no_description"]
    return s.format_map(_Safe(params))


def placeholders(s: str) -> set:
    return set(re.findall(r"\{(\w+)\}", s))
